### ISSUE TITLE
Relatively Serious Crashing Problem

### ISSUE THREAD

**Issue by Alchemek** [samcv/brainworkshop#24]
Hi,

I'm running Arch Linux x86_64 at a relatively recent update with the git archive from this week. I am running into a relatively serious crashing problem. I am playing standard mode, and it crashes about 33% to 40% of the time based on 20 trials. I don't know if it has something to do with avbin not working properly (since I don't hear music, despite the fact that I did install avbin7 from the AUR) or if it's something else. Is there a log that I can provide that can help provide insight into this problem? It's very important to me that brainworkshop works well on Arch Linux and it makes very much sense to me that this version of the software works well in general.

Keep in mind that I say "relatively", when I refer to the severity of the problem, since my progress in the game actually is saved after each trial, despite the fact that it crashes.

Please note, also, that I have tested the software from the Arch Linux AUR package and through the vanilla Linux tarball on this site. Both exhibit the same problem, so it's not an Arch Linux AUR packaging issue.

Thank you very much,

Timothy Beryl Grahek

**Comment by xantares** [comment]
I got some crash too:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyglet/media/drivers/openal/interface.py", line 474, in data
    al_format = self._format_map[(audio_format.channels, audio_format.sample_size)]
KeyError: (2, 32)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/brainworkshop/brainworkshop.pyw", line 4774, in <module>
    pyglet.app.run()
  File "/usr/lib/python3.8/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/usr/lib/python3.8/site-packages/pyglet/app/base.py", line 167, in run
    timeout = self.idle()
  File "/usr/lib/python3.8/site-packages/pyglet/app/base.py", line 237, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/usr/lib/python3.8/site-packages/pyglet/clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/usr/share/brainworkshop/brainworkshop.pyw", line 4651, in update
    end_session()
  File "/usr/share/brainworkshop/brainworkshop.pyw", line 4004, in end_session
    update_all_labels(do_analysis = True)
  File "/usr/share/brainworkshop/brainworkshop.pyw", line 3906, in update_all_labels
    analysisLabel.update()
  File "/usr/share/brainworkshop/brainworkshop.pyw", line 3349, in update
    stats.submit_session(percent, category_percents)
  File "/usr/share/brainworkshop/brainworkshop.pyw", line 3893, in submit_session
    play_music(percent)
  File "/usr/share/brainworkshop/brainworkshop.pyw", line 1095, in play_music
    musicplayer.play()
  File "/usr/lib/python3.8/site-packages/pyglet/media/player.py", line 248, in play
    self._set_playing(True)
  File "/usr/lib/python3.8/site-packages/pyglet/media/player.py", line 198, in _set_playing
    self._create_audio_player()
  File "/usr/lib/python3.8/site-packages/pyglet/media/player.py", line 364, in _create_audio_player
    self._audio_player = audio_driver.create_audio_player(source, self)
  File "/usr/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 66, in create_audio_player
    return OpenALAudioPlayer(self, source, player)
  File "/usr/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 163, in __init__
    self.refill(self.ideal_buffer_size)
  File "/usr/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 291, in refill
    self._queue_audio_data(audio_data, length)
  File "/usr/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 321, in _queue_audio_data
    buf.data(audio_data, self.source.audio_format, length)
  File "/usr/lib/python3.8/site-packages/pyglet/media/drivers/openal/interface.py", line 476, in data
    raise MediaException('Unsupported sample size')
pyglet.media.exceptions.MediaException: Unsupported sample size
```

**Comment by xantares** [comment]
This happens with pyglet>=1.5.1

**Comment by xantares** [comment]
xref https://github.com/pyglet/pyglet/issues/191

**Comment by xantares** [comment]
@Alchemek please provide a backtrace

**Comment by Alchemek** [comment]
This crash was generated from my first trial this morning.

`Traceback (most recent call last):
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/interface.py", line 474, in data
    al_format = self._format_map[(audio_format.channels, audio_format.sample_size)]
KeyError: (2, 32)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "brainworkshop.pyw", line 4774, in <module>
    pyglet.app.run()
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/app/base.py", line 167, in run
    timeout = self.idle()
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/app/base.py", line 237, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "brainworkshop.pyw", line 4651, in update
    end_session()
  File "brainworkshop.pyw", line 4004, in end_session
    update_all_labels(do_analysis = True)
  File "brainworkshop.pyw", line 3906, in update_all_labels
    analysisLabel.update()
  File "brainworkshop.pyw", line 3349, in update
    stats.submit_session(percent, category_percents)
  File "brainworkshop.pyw", line 3893, in submit_session
    play_music(percent)
  File "brainworkshop.pyw", line 1095, in play_music
    musicplayer.play()
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/media/player.py", line 248, in play
    self._set_playing(True)
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/media/player.py", line 198, in _set_playing
    self._create_audio_player()
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/media/player.py", line 364, in _create_audio_player
    self._audio_player = audio_driver.create_audio_player(source, self)
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 66, in create_audio_player
    return OpenALAudioPlayer(self, source, player)
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 163, in __init__
    self.refill(self.ideal_buffer_size)
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 291, in refill
    self._queue_audio_data(audio_data, length)
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 321, in _queue_audio_data
    buf.data(audio_data, self.source.audio_format, length)
  File "/home/alchemek/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/interface.py", line 476, in data
    raise MediaException('Unsupported sample size')
pyglet.media.exceptions.MediaException: Unsupported sample size`

**Comment by xantares** [comment]
this is fixed in the next pyglet point release, for now we have to work around it with:
```pip install --user git+https://github.com/pyglet/pyglet@pyglet-1.5-maintenance```
