### ISSUE TITLE
Can't run Brainworkshop after updating Mac OS to Big Sur

### ISSUE THREAD

**Issue by lgtout** [samcv/brainworkshop#32]
Hi, 

I'm unable to run Brainworkshop after updating Mac OS to Big Sur. 

Below is the error I get.

Any fixes or workarounds for this?

Thanks much!

>  /Users/bayo/dev/brainworkshop-5/brainworkshop.pyw:44: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import random, os, sys, imp, socket, webbrowser, time, math, traceback, datetime, errno
Error: unable to load pyglet.  If you already installed pyglet, please ensure ctypes is installed.  Please visit http://pyglet.org
Full text of error:
Traceback (most recent call last):
  File "/Users/bayo/dev/brainworkshop-5/brainworkshop.pyw", line 905, in <module>
    from pyglet.gl import *
  File "/usr/local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException
  File "/usr/local/lib/python3.8/site-packages/pyglet/gl/lib.py", line 147, in <module>
    from pyglet.gl.lib_agl import link_GL, link_GLU, link_AGL
  File "/usr/local/lib/python3.8/site-packages/pyglet/gl/lib_agl.py", line 43, in <module>
    gl_lib = pyglet.lib.load_library(framework='/System/Library/Frameworks/OpenGL.framework')
  File "/usr/local/lib/python3.8/site-packages/pyglet/lib.py", line 124, in load_library
    return self.load_framework(kwargs['framework'])
  File "/usr/local/lib/python3.8/site-packages/pyglet/lib.py", line 279, in load_framework
    raise ImportError("Can't find framework %s." % path)
ImportError: Can't find framework /System/Library/Frameworks/OpenGL.framework.

**Comment by lgtout** [comment]
[Seems](https://stackoverflow.com/questions/63475461/unable-to-import-opengl-gl-in-python-on-macos) the location of OpenGL has changed in Big Sur.
After running `pip3 install --upgrade pyglet` to upgrade pyglet from `1.5.7` to `1.5.11`, Brainworkshop is working fine again.
