### ISSUE TITLE
Cannot Install Brainworkshop on Big Sur

### ISSUE THREAD

**Issue by tommy-odom** [samcv/brainworkshop#35]
This is a different bug from the openGL one

> `Tommys-Air:brainworkshop tommyodom$ python3 brainworkshop.pyw
brainworkshop.pyw:44: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import random, os, sys, imp, socket, webbrowser, time, math, traceback, datetime, errno
2021-02-17 18:00:49.603 Python[45790:480356] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/gh/brszh43s1qg2rx34d_1kq1x40000gn/T/com.apple.python3.savedState
Traceback (most recent call last):
  File "brainworkshop.pyw", line 1163, in <module>
    pyglet.gl.glLineWidth(calc_fontsize(2))
  File "/Users/tommyodom/Library/Python/3.8/lib/python/site-packages/pyglet-2.0.dev1-py3.8.egg/pyglet/gl/lib.py", line 114, in errcheck
pyglet.gl.lib.GLException: (0x501): Invalid value. A numeric argument is out of range.`

Is there anything I can do?

**Comment by xantares** [comment]
It could be a pyglet bug, if I google "pyglet.gl.lib.GLException Invalid value" I get a lot of these, please submit a report upstream.

**Comment by xantares** [comment]
also you're using a beta version of  pyglet "2.0.dev1" maybe try to revert to latest stable: 1.5.15
I dont know if brainworkshop will still be compatible with that

**Comment by tommy-odom** [comment]
`pip3 uninstall pyglet `
`pip3 install --upgrade pyglet==1.5.15`

fixed the issue. I should have caught that in the error message. Thanks.
